import { Capability } from "../react/capability/device-capability";
import { AnalogInput, AnalogTemperatureSensor, AnyObjectId, BoilerCascade, Command, ControlDeviceId, HeatingCircuit, HeatingMode, IntervalTimetable, NTCTemperatureCurve, Pump, Pza, ReactionId, RelayControl, Scenario, TemperatureSensorId, TemperatureSettingId, ThreewayTap, TimeInterval, User, WiredTemperatureSensor } from "../react/z3kConfig/z3kConfig";


export const fakeState = {
    // visible: true,
    ui_settings: {
        selected_device_id: 148779,
        selected_tab_key: 'settings',
        zth_dashboard_active: false,
        event_filter: {
            alarm: true,
            blackout: true,
            boilerfail: true,
            callsms: true,
            connection: true,
            filetransfers: true,
            gps: true,
            gsm: true,
            guard: true,
            power: true,
            temperature_alarm: true,
            thermometer_malfunction: true,
            thermometer_update: true,
            zonealarm: true,
        },
        graphs: {
            wheel_zoom: true,
        },
        hide_maintenance_2020_01_20_notice: true,
        leftpanel: {
            collapsed: false,
            width: 375,
        },
        idle_mode_enabled: true,
        hide_sale_2020_07_notice: true,
        period: {
            from: 1613941200,
            to: 1614718799,
        },
        themeType: 2,
    },
    active: true,
    autopayment_enabled: false,
    // dispatch: undefined,
    // large: true,
    server_time: {local: 1617693505, server: 1617693505},
    account_balance: 100_00,
    account: {
        id: 194745,
        username: 'TVP-TEST',
        fullname: 'Владимир',
        phone: '',
        email: 'vladimir@microline.ru',
        email_confirmed: true,
        is_demo: false,
        guest_password_set: true,
        allow_terminal: true,
        show_network_events: false,
        autoscan_system: null,
        public_api_allowed: false,
        zth_dashboard: {
            show: false,
            enable_modes: true,
            enable_zones: true,
            enable_temperature: true,
            enable_alert: true,
        },
        sims: [],
        foreign_sims: [],
        date_last_news_reading: 1615964226,
        webui_beta: false,
        org_details: {inn: '', title: '', address: ''},
        asp_billing: {
            is_dealer: false,
            client_permissions: {
                can_edit_settings: null,
                can_edit_access: null,
                can_add_devices: null,
                can_manage_groups: null,
                show_profile_menu: null,
                show_maintenance_tab: null,
                show_diagnostics: null,
            },
            allow_terminal: false,
        },
        is_guest: false,
        is_staff: true,
        is_superuser: false,
        permissions: ['admin_can_view_sims'],
    },
    r_device: {
        temperature: [null],
        fix_hw205_amr_state: null,
        fuel_consumption: {
            enabled: false,
            idle: null,
            km100: null,
            price: null,
        },
        last_guard_event: {time: 1602676265, event: 'GuardOn'} as const,
        filetransfers: [],
        access: [],
        capabilities: [
            Capability.has_firmware_upgrade,
            Capability.has_gsm,
            Capability.has_gsm_balance,
            Capability.has_guard_notification,
            Capability.has_guard_state,
            Capability.has_multiple_thermometers,
            Capability.has_thermostat,
            Capability.has_thermostat_hysteresis,
            Capability.has_offline_notifications,
            Capability.has_siren_control,
            Capability.has_voltage_sensor,
            Capability.is_fixed_alarm,
            Capability.has_rf,
            Capability.has_external_rf,
            Capability.has_thermometer_functions,
            Capability.has_serverside_events_notifications,
            Capability.no_rf_add_button,
            Capability.no_rf_del_button,
            Capability.has_pza,
            Capability.has_custom_controls_schedule,
            Capability.has_multiple_thermometer_functions,
            Capability.has_sx_config,
            Capability.has_z3k_settings,
            Capability.has_ztc_state_packets,
            Capability.has_sim_in_device,
            Capability.has_climatic_interface,
            Capability.has_alice,
            Capability.has_wifi_v2,
        ],
        // device_type: {code: 'CLIMATIC', name: 'ZONT CLIMATIC'},
        // hardware_type: {code: '620', name: '620'},
        // id: 164364,
        ip: '212.92.175.2',
        is_active: true,
        online: true,
        owner_username: 'TVP-TEST',
        user_id: 194745,
        name: 'Климатик',
        color: '#99540f',
        notes: null,
        // serial: 'B8D8CDB16BAC',
        visible_device_type: null,
        // firmware_version: [145],
        timezone: 3,
        suggest_firmware_upgrade: true,
        graphs_config: {
            blocks: [
                {
                    sources: [
                        {class: 'WiredTemperatureGraphData', params: {object_id: 4100}},
                        {
                            class: 'AnalogTemperatureGraphData',
                            params: {object_id: 20522},
                        },
                        {
                            class: 'AnalogTemperatureGraphData',
                            params: {object_id: 20523},
                        },
                        {
                            class: 'AnalogTemperatureGraphData',
                            params: {object_id: 20524},
                        },
                        {
                            class: 'AnalogTemperatureGraphData',
                            params: {object_id: 20525},
                        },
                        {
                            class: 'AnalogTemperatureGraphData',
                            params: {object_id: 20526},
                        },
                        {
                            class: 'AnalogTemperatureGraphData',
                            params: {object_id: 20527},
                        },
                        {
                            class: 'HeatingCircuitSetpointTempGraphData',
                            params: {object_id: 20494},
                        },
                        {
                            class: 'HeatingCircuitTargetTempGraphData',
                            params: {object_id: 20494},
                        },
                        {
                            class: 'HeatingCircuitWorkTimeGraphData',
                            params: {object_id: 20494},
                        },
                        {
                            class: 'HeatingCircuitSetpointTempGraphData',
                            params: {object_id: 20495},
                        },
                        {
                            class: 'HeatingCircuitTargetTempGraphData',
                            params: {object_id: 20495},
                        },
                        {
                            class: 'HeatingCircuitWorkTimeGraphData',
                            params: {object_id: 20495},
                        },
                        {
                            class: 'HeatingCircuitSetpointTempGraphData',
                            params: {object_id: 20496},
                        },
                        {
                            class: 'HeatingCircuitTargetTempGraphData',
                            params: {object_id: 20496},
                        },
                        {
                            class: 'HeatingCircuitWorkTimeGraphData',
                            params: {object_id: 20496},
                        },
                        {
                            class: 'HeatingCircuitSetpointTempGraphData',
                            params: {object_id: 20497},
                        },
                        {
                            class: 'HeatingCircuitTargetTempGraphData',
                            params: {object_id: 20497},
                        },
                        {
                            class: 'HeatingCircuitWorkTimeGraphData',
                            params: {object_id: 20497},
                        },
                        {
                            class: 'HeatingCircuitSetpointTempGraphData',
                            params: {object_id: 20498},
                        },
                        {
                            class: 'HeatingCircuitTargetTempGraphData',
                            params: {object_id: 20498},
                        },
                        {
                            class: 'HeatingCircuitWorkTimeGraphData',
                            params: {object_id: 20498},
                        },
                        {
                            class: 'HeatingCircuitSetpointTempGraphData',
                            params: {object_id: 20499},
                        },
                        {
                            class: 'HeatingCircuitTargetTempGraphData',
                            params: {object_id: 20499},
                        },
                        {
                            class: 'HeatingCircuitWorkTimeGraphData',
                            params: {object_id: 20499},
                        },
                    ],
                    height: null,
                    height_mobile: null,
                },
                {
                    sources: [
                        {
                            class: 'AnalogTemperatureGraphData',
                            params: {object_id: 20522},
                        },
                        {
                            class: 'HeatingCircuitSetpointTempGraphData',
                            params: {object_id: 20496},
                        },
                        {
                            class: 'HeatingCircuitTargetTempGraphData',
                            params: {object_id: 20496},
                        },
                        {
                            class: 'HeatingCircuitWorkTimeGraphData',
                            params: {object_id: 20496},
                        },
                    ],
                    height: null,
                    height_mobile: null,
                },
                {
                    sources: [
                        {
                            class: 'AnalogTemperatureGraphData',
                            params: {object_id: 20522},
                        },
                        {
                            class: 'AnalogTemperatureGraphData',
                            params: {object_id: 20527},
                        },
                        {
                            class: 'HeatingCircuitTargetTempGraphData',
                            params: {object_id: 20496},
                        },
                    ],
                    height: null,
                    height_mobile: null,
                },
                {
                    sources: [
                        {
                            class: 'AnalogTemperatureGraphData',
                            params: {object_id: 20522},
                        },
                        {
                            class: 'HeatingCircuitTargetTempGraphData',
                            params: {object_id: 20496},
                        },
                    ],
                    height: null,
                    height_mobile: null,
                },
            ],
        },
        server_notifications: {
            events: {enabled: false},
            offline: {enabled: false, timeout: 1200},
        },
        debug_text_messages_regexp: '.',
        cams: [
            {
                name: '',
                rtsp:
                    'rtsp://viewer:xkcd1855@212.92.175.2:554/cam/realmonitor?channel=9&subtype=0',
                rtspme: 'https://rtsp.me/embed/949He8Rn/',
                use_dynamic_ip: false,
            },
            {name: '', rtsp: '', rtspme: '', use_dynamic_ip: false},
        ],
        sim_in_device: null,
        z3k_config: {
            device: {name: 'CLIMATIC', hardware: '620', firmware: '145'},
            servers: 's1.zont-online.ru,s2.zont-online.ru',
            port: 52200,
            login: 'B8D8CDB16BAC',
            password: 'ao4aqvb0ha5m27ds',
            apn: 'internet.mts.ru',
            timezone: 3,
            gsm_settings: {ussd: '*102#', threshold: 30},
            usbpassword: '0000',
            service_contact: {
                phone: '+78007007291',
                date: {day: 24, month: 7, year: 2021},
            },
            wifi_settings: {netname: 'microline', pass: 'bra8he4e3', is_enabled: true},
            use_reserve_battery: false,
            server_settings: {show_control_devices_state: true},
            analog_inputs: [
                {
                    physical_input_num: 8,
                    name: 'Внешний термостат 1',
                    upper_threshold: 2,
                    lower_threshold: 1,
                    active_level_timeout: 1,
                    inactive_level_timeout: 1,
                    setting_register: 0,
                    notification_list: [],
                    sensor_type: 8,
                    recovery_list: [],
                    upper_notification_list: [],
                    impulse_frequency: 0,
                    calibration: 0,
                    position: 0,
                    units: 0,
                    voltage: -1,
                    id: 20530 as AnalogInput.Id,
                } as const,
                {
                    physical_input_num: 9,
                    name: 'Внешний термостат 2',
                    upper_threshold: 2,
                    lower_threshold: 1,
                    active_level_timeout: 1,
                    inactive_level_timeout: 1,
                    setting_register: 0,
                    notification_list: [],
                    sensor_type: 8,
                    recovery_list: [],
                    upper_notification_list: [],
                    impulse_frequency: 0,
                    calibration: 0,
                    position: 0,
                    units: 0,
                    voltage: -1,
                    id: 20531 as AnalogInput.Id,
                } as const,
                {
                    physical_input_num: 10,
                    name: 'Внешний термостат 3',
                    upper_threshold: 2,
                    lower_threshold: 1,
                    active_level_timeout: 1,
                    inactive_level_timeout: 1,
                    setting_register: 0,
                    notification_list: [],
                    sensor_type: 8,
                    recovery_list: [],
                    upper_notification_list: [],
                    impulse_frequency: 0,
                    calibration: 0,
                    position: 0,
                    units: 0,
                    voltage: -1,
                    id: 20532 as AnalogInput.Id,
                } as const,
                {
                    physical_input_num: 4,
                    name: 'Контроль напряжения питания',
                    upper_threshold: 15,
                    lower_threshold: 10,
                    active_level_timeout: 1,
                    inactive_level_timeout: 1,
                    setting_register: 9,
                    notification_list: [20535] as ReactionId[],
                    sensor_type: 0,
                    recovery_list: [20536] as ReactionId[],
                    upper_notification_list: [],
                    impulse_frequency: 0,
                    calibration: 0,
                    position: 0,
                    units: 0,
                    voltage: -1,
                    id: 20550 as AnalogInput.Id,
                } as const,
                {
                    physical_input_num: 5,
                    name: 'Контроль батареи',
                    upper_threshold: 0,
                    lower_threshold: 0,
                    active_level_timeout: 1,
                    inactive_level_timeout: 1,
                    setting_register: 1,
                    notification_list: [],
                    sensor_type: 0,
                    recovery_list: [],
                    upper_notification_list: [],
                    impulse_frequency: 0,
                    calibration: 0,
                    position: 0,
                    units: 0,
                    voltage: -1,
                    id: 20551 as AnalogInput.Id,
                } as const,
            ],
            wired_temperature_sensors: [
                {
                    serial: '000802FD82A010',
                    name: 'Датчик',
                    upper_threshold: 40,
                    lower_threshold: 5,
                    hysteresis: 1,
                    no_connection_timeout: 5,
                    rol_connection_lost: [20534] as ReactionId[],
                    rol_temperature_upper_threshold: [20553] as ReactionId[],
                    rol_temperature_lower_threshold: [20552] as ReactionId[],
                    io_extension_id: 0,
                    recovery_list: [],
                    setting_register: 0,
                    position: 0,
                    id: 4100 as WiredTemperatureSensor.Id,
                } as const,
            ],
            notifications: [
                {
                    name: 'Неисправность датчика температуры ',
                    setting_register: 17,
                    sms_text: 'Неисправность датчика температуры $name$',
                    voice_text: 'Неисправность_датчика',
                    recipient_list: [20533 as User.Id],
                    id: 20534
                },
                {
                    name: 'Пропадание основного питания',
                    setting_register: 17,
                    sms_text: 'Пропадание основного питания!',
                    voice_text: 'Пропадание_питания',
                    recipient_list: [20533 as User.Id],
                    id: 20535,
                },
                {
                    name: 'Появление основного питания',
                    setting_register: 1,
                    sms_text: 'Появление основного питания!',
                    voice_text: 'Появление_питания',
                    recipient_list: [20533 as User.Id],
                    id: 20536,
                },
                {
                    name: 'Ошибка котла',
                    setting_register: 17,
                    sms_text: 'Ошибка котла $name$ №$value$',
                    voice_text: 'Ошибка котла',
                    recipient_list: [20533 as User.Id],
                    id: 20537 ,
                },
                {
                    name: 'Пропадание связи с устройством',
                    setting_register: 17,
                    sms_text: '$name$ -- нет соединения!',
                    voice_text: 'Нет_связи_с_устройством',
                    recipient_list: [20533 as User.Id],
                    id: 20538,
                },
                {
                    name: 'Баланс ниже порога',
                    setting_register: 1,
                    sms_text: 'Баланс ниже порога! $value$',
                    voice_text: 'Баланс_ниже_порога',
                    recipient_list: [20533 as User.Id],
                    id: 20539,
                },
                {
                    name: 'Температура ниже порога',
                    setting_register: 17,
                    sms_text: '$name$ -- температура ниже порога! $value$',
                    voice_text: 'Температура_ниже_порога',
                    recipient_list: [20533 as User.Id],
                    id: 20552,
                },
                {
                    name: 'Температура выше порога',
                    setting_register: 17,
                    sms_text: '$name$ -- температура выше порога! $value$',
                    voice_text: 'Температура_выше_порога',
                    recipient_list: [20533 as User.Id],
                    id: 20553,
                },
            ],
            users: [
                {
                    name: 'Пользователь',
                    phone: '',
                    key_and_radiotag_list: [],
                    role_list: [],
                    password: '',
                    setting_register: 6,
                    id: 20533 as User.Id,
                },
            ],
            commands: [
                {
                    name: 'Включить режим комфорт',
                    objectid: 20501 as AnyObjectId,
                    cmd: '1',
                    id: 20544 as Command.Id,
                },
                {
                    name: 'Включить режим эконом',
                    objectid: 20502 as AnyObjectId,
                    cmd: '1',
                    id: 20545 as Command.Id,
                },
                {
                    name: 'Включить режим расписание',
                    objectid: 20503 as AnyObjectId,
                    cmd: '1',
                    id: 20546 as Command.Id,
                },
                {
                    name: 'Включить режим отключено',
                    objectid: 20504 as AnyObjectId,
                    cmd: '1',
                    id: 20547 as Command.Id,
                },
                {
                    name: 'Включить режим нагрев ГВС',
                    objectid: 20505 as AnyObjectId,
                    cmd: '1',
                    id: 20548 as Command.Id,
                },
                {
                    name: 'Отключить режим нагрев ГВС',
                    objectid: 20499 as AnyObjectId,
                    cmd: '20504',
                    id: 20549 as Command.Id,
                },
            ],
            scenarios: [
                {
                    name: 'КОМФОРТ',
                    links: [20544, 20548] as ReactionId[],
                    timetable: {checked: false, weekday_register: 0, time: 0},
                    rest: [0, 0, 0],
                    id: 20540 as Scenario.Id,
                },
                {
                    name: 'ЭКОНОМ',
                    links: [20545, 20549] as ReactionId[],
                    timetable: {checked: false, weekday_register: 0, time: 0},
                    rest: [0, 0, 0],
                    id: 20541 as Scenario.Id,
                },
                {
                    name: 'РАСПИСАНИЕ',
                    links: [20546] as ReactionId[],
                    timetable: {checked: false, weekday_register: 0, time: 0},
                    rest: [0, 0, 0],
                    id: 20542 as Scenario.Id,
                },
                {
                    name: 'ВЫКЛЮЧЕНО',
                    links: [20547] as ReactionId[],
                    timetable: {checked: false, weekday_register: 0, time: 0},
                    rest: [0, 0, 0],
                    id: 20543 as Scenario.Id,
                },
            ],
            relay_controls: [
                {
                    name: 'Управление котлом 1',
                    physical_output: 12,
                    setting_register: 0,
                    id: 20488 as RelayControl.Id,
                },
                {
                    name: 'Управление котлом 2',
                    physical_output: 13,
                    setting_register: 0,
                    id: 20489 as RelayControl.Id,
                },
            ],
            threeway_taps: [
                {
                    name: 'Смеситель контура 1',
                    physical_output1: 4,
                    physical_output2: 3,
                    step_time: 1,
                    closing_time: 120,
                    coefficient: 0,
                    setting_register: 0,
                    step_period: 10,
                    id: 20491 as ThreewayTap.Id,
                },
                {
                    name: 'Смеситель контура 2',
                    physical_output1: 7,
                    physical_output2: 6,
                    step_time: 2,
                    closing_time: 120,
                    coefficient: 0.2,
                    setting_register: 13,
                    step_period: 10,
                    id: 20492 as ThreewayTap.Id,
                },
                {
                    name: 'Смеситель контура 3',
                    physical_output1: 10,
                    physical_output2: 9,
                    step_time: 2,
                    closing_time: 130,
                    coefficient: 0,
                    setting_register: 0,
                    step_period: 10,
                    id: 20493 as ThreewayTap.Id,
                },
            ],
            heating_circuits: [
                {
                    id: 20494 as HeatingCircuit.Id,

                    name: 'Котёл1',
                    type: 0 as HeatingCircuit.Type,
                    setting_register: 4,
                    external_thermostat: null,
                    pza: 0 as Pza.Id,
                    heat_source: null,
                    control_devices: [20488] as ControlDeviceId[],

                    water_temp_sensor: 20527 as TemperatureSensorId,
                    water_temp_sensor_reserve: null,

                    water_min_temperature: 15,
                    water_max_temperature: 80,

                    air_temp_sensor: null,
                    air_temp_sensor_reserve: null,

                    dhw_temp_sensor: null,
                    dhw_temp_sensor_reserve: null,

                    winter_summer_switch: false,
                    summer_threshold: null,

                    hysteresis: 2,
                    heat_request: 0,
                    turn_off_delay: 0,

                    antileg_mode_options: {m: 0, h: 0, days: 0},

                    position: 0,
                    locker_id: null,
                    delta_temp: 0,
                },
                {
                    name: 'котёл2',
                    type: 0 as HeatingCircuit.Type,
                    water_min_temperature: 15,
                    water_max_temperature: 80,
                    air_temp_sensor: null,
                    air_temp_sensor_reserve: null,
                    dhw_temp_sensor: null,
                    dhw_temp_sensor_reserve: null,
                    water_temp_sensor: 20527 as TemperatureSensorId,
                    water_temp_sensor_reserve: null,
                    hysteresis: 1.5,
                    control_devices: [20489] as ControlDeviceId[],
                    setting_register: 4,
                    turn_off_delay: 0,
                    external_thermostat: null,
                    heat_request: 0,
                    pza: 0 as Pza.Id,
                    heat_source: null,
                    antileg_mode_options: {m: 0, h: 0, days: 0},
                    summer_threshold: null,
                    winter_summer_switch: false,
                    position: 0,
                    locker_id: null,
                    delta_temp: 0,
                    id: 20495 as HeatingCircuit.Id,
                },
                {
                    name: 'Радиаторы',
                    type: 3 as HeatingCircuit.Type,
                    water_min_temperature: 15,
                    water_max_temperature: 80,
                    air_temp_sensor: 4100 as TemperatureSensorId,
                    air_temp_sensor_reserve: null,
                    dhw_temp_sensor: null,
                    dhw_temp_sensor_reserve: null,
                    water_temp_sensor: 20522 as TemperatureSensorId,
                    water_temp_sensor_reserve: null,
                    hysteresis: 0.5,
                    control_devices: [20485] as ControlDeviceId[],
                    setting_register: 9,
                    turn_off_delay: 0,
                    external_thermostat: null,
                    heat_request: 2730,
                    pza: 0 as Pza.Id,
                    heat_source: 20500,
                    antileg_mode_options: {m: 0, h: 0, days: 0},
                    summer_threshold: null,
                    winter_summer_switch: false,
                    position: 0,
                    locker_id: null,
                    delta_temp: 0,
                    id: 20496 as HeatingCircuit.Id,
                },
                {
                    name: 'Контур 2',
                    type: 3 as HeatingCircuit.Type,
                    water_min_temperature: 15,
                    water_max_temperature: 80,
                    air_temp_sensor: null,
                    air_temp_sensor_reserve: null,
                    dhw_temp_sensor: null,
                    dhw_temp_sensor_reserve: null,
                    water_temp_sensor: 20523 as TemperatureSensorId,
                    water_temp_sensor_reserve: null,
                    hysteresis: 0.5,
                    control_devices: [20486, 20492] as ControlDeviceId[],
                    setting_register: 10,
                    turn_off_delay: 0,
                    external_thermostat: null,
                    heat_request: 2730,
                    pza: 255 as Pza.Id,
                    heat_source: 20500,
                    antileg_mode_options: {m: 0, h: 0, days: 0},
                    summer_threshold: null,
                    winter_summer_switch: false,
                    position: 0,
                    locker_id: null,
                    delta_temp: 0,
                    id: 20497 as HeatingCircuit.Id,
                },
                {
                    name: 'Контур 3',
                    type: 3 as HeatingCircuit.Type,
                    water_min_temperature: 15,
                    water_max_temperature: 80,
                    air_temp_sensor: null,
                    air_temp_sensor_reserve: null,
                    dhw_temp_sensor: null,
                    dhw_temp_sensor_reserve: null,
                    water_temp_sensor: 20524 as TemperatureSensorId,
                    water_temp_sensor_reserve: null,
                    hysteresis: 0.5,
                    control_devices: [20487, 20493] as ControlDeviceId[],
                    setting_register: 10,
                    turn_off_delay: 0,
                    external_thermostat: null,
                    heat_request: 700,
                    pza: 255 as Pza.Id,
                    heat_source: 20500,
                    antileg_mode_options: {m: 0, h: 0, days: 0},
                    summer_threshold: null,
                    winter_summer_switch: false,
                    position: 0,
                    locker_id: null,
                    delta_temp: 0,
                    id: 20498 as HeatingCircuit.Id,
                },
                {
                    name: 'ГВС',
                    type: 1 as HeatingCircuit.Type,
                    water_min_temperature: null,
                    water_max_temperature: null,
                    air_temp_sensor: null,
                    air_temp_sensor_reserve: null,
                    dhw_temp_sensor: 20525 as TemperatureSensorId,
                    dhw_temp_sensor_reserve: null,
                    water_temp_sensor: null,
                    water_temp_sensor_reserve: null,
                    hysteresis: 4,
                    control_devices: [20483] as ControlDeviceId[],
                    setting_register: 16,
                    turn_off_delay: 0,
                    external_thermostat: null,
                    heat_request: 65535,
                    pza: 255 as Pza.Id,
                    heat_source: 20500,
                    antileg_mode_options: {h: 4, m: 0, days: 129},
                    summer_threshold: null,
                    winter_summer_switch: false,
                    position: 0,
                    locker_id: null,
                    delta_temp: 0,
                    id: 20499 as HeatingCircuit.Id,
                },
            ],
            pumps: [
                {
                    name: 'Загрузка ГВС',
                    physical_output: 1,
                    delay: 0,
                    setting_register: 1,
                    pressure_sensor: null,
                    pressure_threshold: -273,
                    id: 20483 as Pump.Id,
                },
                {
                    name: 'ЦН ГВС',
                    physical_output: 2,
                    delay: 0,
                    setting_register: 1,
                    pressure_sensor: null,
                    pressure_threshold: -273,
                    id: 20484 as Pump.Id,
                },
                {
                    name: 'Насос контура 1',
                    physical_output: 5,
                    delay: 0,
                    setting_register: 1,
                    pressure_sensor: null,
                    pressure_threshold: -273,
                    id: 20485 as Pump.Id,
                },
                {
                    name: 'Насос контура 2',
                    physical_output: 8,
                    delay: 0,
                    setting_register: 0,
                    pressure_sensor: null,
                    pressure_threshold: -273,
                    id: 20486 as Pump.Id,
                },
                {
                    name: 'Насос контура 3',
                    physical_output: 11,
                    delay: 0,
                    setting_register: 0,
                    pressure_sensor: null,
                    pressure_threshold: -273,
                    id: 20487 as Pump.Id,
                },
            ],
            heating_modes: [
                {
                    name: 'Комфорт',
                    heating_zones: [
                        {
                            heating_circuit: 20496 as HeatingCircuit.Id,
                            temperature_setting: 3030 as TemperatureSettingId,
                            adjusting_sensor: null,
                            pza: null,
                        },
                        {
                            heating_circuit: 20497 as HeatingCircuit.Id,
                            temperature_setting: 3030 as TemperatureSettingId,
                            adjusting_sensor: null,
                            pza: null,
                        },
                        {
                            heating_circuit: 20498 as HeatingCircuit.Id,
                            temperature_setting: 3030 as TemperatureSettingId,
                            adjusting_sensor: null,
                            pza: null,
                        },
                    ],
                    setting_register: 0,
                    water_sensor: null,
                    start_reserve_delay: 0,
                    hysteresis: 1,
                    position: 0,
                    id: 20501 as HeatingMode.Id,
                },
                {
                    name: 'Эконом',
                    heating_zones: [
                        {
                            heating_circuit: 20496 as HeatingCircuit.Id,
                            temperature_setting: 2920 as TemperatureSettingId,
                            adjusting_sensor: null,
                            pza: null,
                        },
                        {
                            heating_circuit: 20497 as HeatingCircuit.Id,
                            temperature_setting: 2930 as TemperatureSettingId,
                            adjusting_sensor: null,
                            pza: null,
                        },
                        {
                            heating_circuit: 20498 as HeatingCircuit.Id,
                            temperature_setting: 2930 as TemperatureSettingId,
                            adjusting_sensor: null,
                            pza: null,
                        },
                    ],
                    setting_register: 0,
                    start_reserve_delay: 0,
                    water_sensor: null,
                    hysteresis: 1,
                    position: 0,
                    id: 20502 as HeatingMode.Id,
                },
                {
                    name: 'Расписание',
                    heating_zones: [
                        {
                            heating_circuit: 20496 as HeatingCircuit.Id,
                            temperature_setting: 20518 as TemperatureSettingId,
                            adjusting_sensor: null,
                            pza: null,
                        },
                        {
                            heating_circuit: 20497 as HeatingCircuit.Id,
                            temperature_setting: 20519 as TemperatureSettingId,
                            adjusting_sensor: null,
                            pza: null,
                        },
                        {
                            heating_circuit: 20498 as HeatingCircuit.Id,
                            temperature_setting: 20520 as TemperatureSettingId,
                            adjusting_sensor: null,
                            pza: null,
                        },
                        {
                            heating_circuit: 20499 as HeatingCircuit.Id,
                            temperature_setting: 20521 as TemperatureSettingId,
                            adjusting_sensor: null,
                            pza: null,
                        },
                    ],
                    setting_register: 0,
                    start_reserve_delay: 0,
                    water_sensor: null,
                    hysteresis: 1,
                    position: 0,
                    id: 20503 as HeatingMode.Id,
                },
                {
                    name: 'Выкл',
                    heating_zones: [
                        {
                            heating_circuit: 20496 as HeatingCircuit.Id,
                            temperature_setting: 0,
                            adjusting_sensor: null,
                            pza: null,
                        },
                        {
                            heating_circuit: 20497 as HeatingCircuit.Id,
                            temperature_setting: 0,
                            adjusting_sensor: null,
                            pza: null,
                        },
                        {
                            heating_circuit: 20498 as HeatingCircuit.Id,
                            temperature_setting: 0,
                            adjusting_sensor: null,
                            pza: null,
                        },
                        {
                            heating_circuit: 20499 as HeatingCircuit.Id,
                            temperature_setting: 0,
                            adjusting_sensor: null,
                            pza: null,
                        },
                    ],
                    setting_register: 0,
                    start_reserve_delay: 0,
                    water_sensor: null,
                    hysteresis: 1,
                    position: 0,
                    id: 20504 as HeatingMode.Id,
                },
                {
                    name: 'Нагрев ГВС',
                    heating_zones: [
                        {
                            heating_circuit: 20499 as HeatingCircuit.Id,
                            temperature_setting: 3380 as TemperatureSettingId,
                            adjusting_sensor: null,
                            pza: null,
                        },
                    ],
                    setting_register: 0,
                    start_reserve_delay: 0,
                    water_sensor: null,
                    hysteresis: 1,
                    position: 0,
                    id: 20505 as HeatingMode.Id,
                },
            ],
            analog_temperature_sensors: [
                {
                    physical_input_num: 1,
                    name: 'tтн Радиаторы',
                    type: AnalogTemperatureSensor.Type.NTC10,
                    upper_threshold: 87,
                    lower_threshold: 8,
                    hysteresis: 0,
                    no_connection_timeout: 1,
                    rol_connection_lost: [20534] as ReactionId[],
                    rol_temperature_upper_threshold: [20553] as ReactionId[],
                    rol_temperature_lower_threshold: [20552] as ReactionId[],
                    ntc: 20529 as NTCTemperatureCurve.Id,
                    pull_up: 0,
                    calibration_shift: 0,
                    recovery_list: [],
                    setting_register: 0,
                    position: 0,
                    id: 20522 as AnalogTemperatureSensor.Id,
                },
                {
                    physical_input_num: 2,
                    name: 'tтн Контур 2',
                    type: AnalogTemperatureSensor.Type.NTC10,
                    upper_threshold: 87,
                    lower_threshold: 8,
                    hysteresis: 0,
                    no_connection_timeout: 1,
                    rol_connection_lost: [20534] as ReactionId[],
                    rol_temperature_upper_threshold: [20553] as ReactionId[],
                    rol_temperature_lower_threshold: [20552] as ReactionId[],
                    ntc: 20529 as NTCTemperatureCurve.Id,
                    pull_up: 0,
                    calibration_shift: 5,
                    recovery_list: [],
                    setting_register: 0,
                    position: 0,
                    id: 20523 as AnalogTemperatureSensor.Id,
                },
                {
                    physical_input_num: 3,
                    name: 'tтн Контур 3',
                    type: AnalogTemperatureSensor.Type.NTC10,
                    upper_threshold: 87,
                    lower_threshold: 8,
                    hysteresis: 0,
                    no_connection_timeout: 1,
                    rol_connection_lost: [20534] as ReactionId[],
                    rol_temperature_upper_threshold: [20553] as ReactionId[],
                    rol_temperature_lower_threshold: [20552] as ReactionId[],
                    ntc: 20529 as NTCTemperatureCurve.Id,
                    pull_up: 0,
                    calibration_shift: 0,
                    recovery_list: [],
                    setting_register: 0,
                    position: 0,
                    id: 20524 as AnalogTemperatureSensor.Id,
                },
                {
                    physical_input_num: 0,
                    name: 't ГВС',
                    type: AnalogTemperatureSensor.Type.NTC10,
                    upper_threshold: 85,
                    lower_threshold: 5,
                    hysteresis: 0,
                    no_connection_timeout: 1,
                    rol_connection_lost: [20534] as ReactionId[],
                    rol_temperature_upper_threshold: [20553] as ReactionId[],
                    rol_temperature_lower_threshold: [20552] as ReactionId[],
                    ntc: 20529 as NTCTemperatureCurve.Id,
                    pull_up: 0,
                    calibration_shift: 0,
                    recovery_list: [],
                    setting_register: 0,
                    position: 0,
                    id: 20525 as AnalogTemperatureSensor.Id,
                },
                {
                    physical_input_num: 6,
                    name: 'Уличный',
                    type: AnalogTemperatureSensor.Type.NTC10,
                    upper_threshold: '',
                    lower_threshold: '',
                    hysteresis: 0,
                    no_connection_timeout: 1,
                    rol_connection_lost: [20534] as ReactionId[],
                    rol_temperature_upper_threshold: [20553] as ReactionId[],
                    rol_temperature_lower_threshold: [20552] as ReactionId[],
                    ntc: 20529 as NTCTemperatureCurve.Id,
                    pull_up: 0,
                    calibration_shift: 5,
                    recovery_list: [],
                    setting_register: 1,
                    position: 0,
                    id: 20526 as AnalogTemperatureSensor.Id,
                } as const,
                {
                    physical_input_num: 7,
                    name: 'Теплоноситель',
                    type: AnalogTemperatureSensor.Type.NTC10,
                    upper_threshold: 85,
                    lower_threshold: 5,
                    hysteresis: 0,
                    no_connection_timeout: 1,
                    rol_connection_lost: [20534] as ReactionId[],
                    rol_temperature_upper_threshold: [20553] as ReactionId[],
                    rol_temperature_lower_threshold: [20552] as ReactionId[],
                    ntc: 20529 as NTCTemperatureCurve.Id,
                    pull_up: 0,
                    calibration_shift: -5,
                    recovery_list: [],
                    setting_register: 0,
                    position: 0,
                    id: 20527 as AnalogTemperatureSensor.Id,
                },
            ],
            ntc_temperature_curves: [
                {
                    x: [
                        176680,
                        96970,
                        55300,
                        32650,
                        19900,
                        12490,
                        10000,
                        8060,
                        5320,
                        3600,
                        2490,
                        1750,
                        1260,
                        920,
                        680,
                        510,
                        390,
                    ],
                    y: [
                        -30,
                        -20,
                        -10,
                        0,
                        10,
                        20,
                        25,
                        30,
                        40,
                        50,
                        60,
                        70,
                        80,
                        90,
                        100,
                        110,
                        120,
                    ],
                    id: 20529 as NTCTemperatureCurve.Id,
                },
            ],
            time_intervals: [
                {
                    sm: 0,
                    sh: 0,
                    em: 0,
                    eh: 7,
                    temperature: 20501 as HeatingMode.Id,
                    action_register: 95,
                    id: 20506 as TimeInterval.Id,
                },
                {
                    sm: 0,
                    sh: 7,
                    em: 0,
                    eh: 23,
                    temperature: 20502 as HeatingMode.Id,
                    action_register: 127,
                    id: 20507 as TimeInterval.Id,
                },
                {
                    sm: 0,
                    sh: 0,
                    em: 0,
                    eh: 0,
                    temperature: 20504 as HeatingMode.Id,
                    action_register: 0,
                    id: 20508 as TimeInterval.Id,
                },
                {
                    sm: 0,
                    sh: 23,
                    em: 0,
                    eh: 7,
                    temperature: 20501 as HeatingMode.Id,
                    action_register: 127,
                    id: 20509 as TimeInterval.Id,
                },
                {
                    sm: 0,
                    sh: 7,
                    em: 0,
                    eh: 23,
                    temperature: 20502 as HeatingMode.Id,
                    action_register: 127,
                    id: 20510 as TimeInterval.Id,
                },
                {
                    sm: 0,
                    sh: 0,
                    em: 0,
                    eh: 0,
                    temperature: 20504 as HeatingMode.Id,
                    action_register: 0,
                    id: 20511 as TimeInterval.Id,
                },
                {
                    sm: 0,
                    sh: 23,
                    em: 0,
                    eh: 7,
                    temperature: 20501 as HeatingMode.Id,
                    action_register: 127,
                    id: 20512 as TimeInterval.Id,
                },
                {
                    sm: 0,
                    sh: 7,
                    em: 0,
                    eh: 23,
                    temperature: 20502 as HeatingMode.Id,
                    action_register: 127,
                    id: 20513 as TimeInterval.Id,
                },
                {
                    sm: 0,
                    sh: 0,
                    em: 0,
                    eh: 0,
                    temperature: 20504 as HeatingMode.Id,
                    action_register: 0,
                    id: 20514 as TimeInterval.Id,
                },
                {
                    sm: 0,
                    sh: 5,
                    em: 0,
                    eh: 9,
                    temperature: 20505 as HeatingMode.Id,
                    action_register: 31,
                    id: 20515 as TimeInterval.Id,
                },
                {
                    sm: 0,
                    sh: 18,
                    em: 0,
                    eh: 22,
                    temperature: 20505 as HeatingMode.Id,
                    action_register: 31,
                    id: 20516 as TimeInterval.Id,
                },
                {
                    sm: 0,
                    sh: 6,
                    em: 0,
                    eh: 22,
                    temperature: 20505 as HeatingMode.Id,
                    action_register: 96,
                    id: 20517 as TimeInterval.Id,
                },
            ],
            interval_timetables: [
                {
                    time_intervals: [20506, 20507, 20508] as TimeInterval.Id[],
                    outside_default: 20504 as HeatingMode.Id,
                    setting_register: 0,
                    id: 20518 as IntervalTimetable.Id,
                },
                {
                    time_intervals: [20509, 20510, 20511] as TimeInterval.Id[],
                    outside_default: 20504 as HeatingMode.Id,
                    setting_register: 0,
                    id: 20519 as IntervalTimetable.Id,
                },
                {
                    time_intervals: [20512, 20513, 20514] as TimeInterval.Id[],
                    outside_default: 20504 as HeatingMode.Id,
                    setting_register: 0,
                    id: 20520 as IntervalTimetable.Id,
                },
                {
                    time_intervals: [20515, 20516, 20517] as TimeInterval.Id[],
                    outside_default: 20504 as HeatingMode.Id,
                    setting_register: 0,
                    id: 20521 as IntervalTimetable.Id,
                },
            ],
            boiler_cascades: [
                {
                    name: 'Каскад',
                    boiler_list: [20494, 20495] as HeatingCircuit.Id[],
                    rotation_period: 1,
                    slave_boiler_start_delay: 40,
                    slave_boiler_finish_delay: 20,
                    water_sensor: 20527 as TemperatureSensorId,
                    setting_register: 0,
                    lead_boiler_switch_delay: 5,
                    hysteresis: 5,
                    id: 20500 as BoilerCascade.Id,
                },
            ],
            counters: {'1': 10, '2': 0, '3': 0},
            unknown: [
                '#S210=4,4294967295,4294967295,4294967295',
                "#Z4097=39,'36','Панель CliMatic',15,20494",
                "#Z4103=39,'45368','Панель CliMatic',15,20494",
                "#Z4104=39,'44757','Панель CliMatic',15,20494",
                "#Z4105=39,'63585','Панель CliMatic',15,20498",
            ],
        },
        tempstep: 1,
        asp_billing: {in_service: true, allowed_for_user: true},
        z3k_state: {
            '4100': {
                curr_temp: 26.3,
                prev_temp: 25.899999999999977,
                flag: 256,
                sensor_ok: true,
            },
            '20483': {
                run: false,
                turn_on: false,
                turn_off: false,
                request: false,
                lock: true,
                state_switched: true,
                summer_mode: false,
                summer_turnover: false,
                test_mode: false,
            },
            '20484': {
                run: false,
                turn_on: false,
                turn_off: false,
                request: false,
                lock: false,
                state_switched: true,
                summer_mode: false,
                summer_turnover: false,
                test_mode: false,
            },
            '20485': {
                run: false,
                turn_on: false,
                turn_off: false,
                request: false,
                lock: false,
                state_switched: true,
                summer_mode: false,
                summer_turnover: false,
                test_mode: false,
            },
            '20486': {
                run: true,
                turn_on: false,
                turn_off: false,
                request: true,
                lock: false,
                state_switched: false,
                summer_mode: false,
                summer_turnover: false,
                test_mode: false,
            },
            '20487': {
                run: true,
                turn_on: false,
                turn_off: false,
                request: true,
                lock: false,
                state_switched: false,
                summer_mode: false,
                summer_turnover: false,
                test_mode: false,
            },
            '20488': {
                active: true,
                set_failed: false,
                test_mode: false,
                test_pending: false,
            },
            '20489': {
                active: true,
                set_failed: false,
                test_mode: false,
                test_pending: false,
            },
            '20491': {
                direction: 0,
                fully_open: false,
                fully_closed: false,
                full_turn: false,
                open_direction: false,
                period_ready: true,
                sensor_fault: false,
                set_output_fault: false,
                set_failed: false,
                test_mode: false,
                test_calibration: false,
            },
            '20492': {
                direction: 2,
                fully_open: false,
                fully_closed: false,
                full_turn: false,
                open_direction: false,
                period_ready: false,
                sensor_fault: false,
                set_output_fault: false,
                set_failed: false,
                test_mode: false,
                test_calibration: false,
            },
            '20493': {
                direction: 0,
                fully_open: false,
                fully_closed: true,
                full_turn: false,
                open_direction: false,
                period_ready: false,
                sensor_fault: false,
                set_output_fault: false,
                set_failed: false,
                test_mode: false,
                test_calibration: false,
            },
            '20494': {
                setpoint_temp: 70,
                target_temp: 20,
                mode_id: 0,
                target_sensor_id: 20527,
                status: 1,
                worktime: 60,
            },
            '20495': {
                setpoint_temp: 70,
                target_temp: 20,
                mode_id: 0,
                target_sensor_id: 20527,
                status: 1,
                worktime: 60,
            },
            '20496': {
                setpoint_temp: 15,
                target_temp: 19,
                mode_id: 20502,
                target_sensor_id: 4100,
                status: 0,
                worktime: 0,
            },
            '20497': {
                setpoint_temp: 20,
                target_temp: 20,
                mode_id: 20502,
                target_sensor_id: 20523,
                status: 0,
                worktime: 60,
            },
            '20498': {
                setpoint_temp: 20,
                target_temp: 20,
                mode_id: 20502,
                target_sensor_id: 20524,
                status: 0,
                worktime: 60,
            },
            '20499': {
                setpoint_temp: 65,
                target_temp: null,
                mode_id: 20504,
                target_sensor_id: 20525,
                status: 4,
                worktime: 0,
            },
            '20522': {
                curr_temp: 25.9,
                prev_temp: 25.600000000000023,
                flag: 160,
                sensor_ok: true,
            },
            '20523': {
                curr_temp: 30.9,
                prev_temp: 30.600000000000023,
                flag: 160,
                sensor_ok: true,
            },
            '20524': {
                curr_temp: 25.8,
                prev_temp: 25.399999999999977,
                flag: 160,
                sensor_ok: true,
            },
            '20525': {curr_temp: 26.4, prev_temp: 26, flag: 160, sensor_ok: true},
            '20526': {
                curr_temp: 31.5,
                prev_temp: 31.100000000000023,
                flag: 160,
                sensor_ok: true,
            },
            '20527': {
                curr_temp: 21.5,
                prev_temp: 21.100000000000023,
                flag: 160,
                sensor_ok: true,
            },
            '20530': {voltage: 0, flag: 4},
            '20531': {voltage: 0, flag: 4},
            '20532': {voltage: 0, flag: 4},
            '20550': {voltage: 11.8, flag: 4},
            '20551': {voltage: 4.1, flag: 4},
        },
        voltage: 11.8,
        power_source: 'main',
        gsm_state: {level: 26, state: 'not-registered', operator: ''},
        wifi_state: {con_stat: 8, rssi: 56},
        last_connect_time: 1617777740,
    },
    billing: {
        billing_type: 'zont',
        dialog_open: false,
        topup_dialog_open: false,
        topup_dialog_randomKey: '0.7406592624117867',
        topup_dialog_suggested_amount_x100: null,
        topup_dialog_pay_intent: null,
        buy_history_dialog_open: false,
        topup_loading: false,
        topup_success: null,
        topup_fail: null,
        buy_history_loading: false,
        buy_history_success: false,
        buy_history_fail: null,
        billing_state: {
            change_no: 10,
            balance_x100: 0,
            ml_balance_x100: 0,
            old_free: true,
            last_day_price_x100: 100,
            charged_up_to: 0,
            additional_history_months: 0,
            post_pay: false,
            credit_limit_amount_x100: 0,
            blocked: false,
            history_months: 3,
        },
        billing_settings: {
            paid: true,
            last_payment_method: 'yakassa',
        },
        day_price_for_user_x100: 0,
        devs_to_charge_for_user: 0,
        h2000plus_firmware: {
            dialog_open: false,
            loading: false,
            success: false,
            fail: null,
        },
    },
    app_settings: {
        dialog_open: false,
        settings: {
            longpress: true,
            widget_device_ids: [],
            pin: null,
            require_fingerprint: false,
            push_sound: {
                remote_id: null,
                local_id: null,
                title: null,
            },
        },
    },
    terminal: {
        1: [
            {
                request_id: '4389408311995704',
                request_time: 1628253461041,
                request: 'GETALLSTATE?',
            },
        ],
    },
};
